spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}

basic:
  ribbon:
    eureka:
      enabled: false
    NIWSServerListClassName: com.example.additional.config.ConsulServerList
    ServerListRefreshInterval: 1000

ribbon:
  client:
    name: ${RIBBON_NAME:client}