eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

spring:
  cloud:
    consul:
      discovery:
        enabled: true
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - id: additional
          uri: lb://additional
          predicates:
            - Path=/api/v1/ebay/**
          order: 0
        - id: basic
          uri: lb://basic
          predicates:
            - Path=/api/v1/**
          order: 1